export const all_roi_tracks = [
  {
    "name": 'Non-reference germline L1 insertions (KNRGL called by Megane)',
    'url': "./rois/megane_KNRGL_calls/AllDonors.KNRGL_merged.slop0.bed",
    'indexed': false,
    'color': "rgba(99,99,99,0.5)",
    'format': 'bed',
    'tracktype':'ROI',
    'donor':'all',
    'tissue':'all'
  },
  {
    name: "Our insertion calls using all scSLAVseq R1 reads",
    'url': './rois/scL1_inserts_calls.bed',
    'indexed': false,
    'color': "rgba(1,1,255,0.5)",
    'format': 'bed',
    'tracktype':'ROI',
    'donor':'all',
    'tissue':'all'
  },
  {
    name: "All of our scSLAVseq peaks",
    'url': './rois/AllDonors.q30_mindist40000_thresh3.filtered.no_rmsk.bed',
    'indexed': false,
    'color': "rgba(1,1,255,0.5)",
    'format': 'bed',
    'tracktype':'ROI',
    'donor':'all',
    'tissue':'all'
  },
  {
    name: "Our bulkSLAVseq peaks",
    'url': './rois/gDNA.AllDonors.slop2500bp_merged.no_rmsk.bed',
    'indexed': false,
    'color': "rgba(1,1,255,0.5)",
    'format': 'bed',
    'tracktype':'ROI',
    'donor':'all',
    'tissue':'all'
  },
  {
    name: "Apua's peak calls",
    'url': './rois/apua_calls_chm13.bed',
    'indexed': false,
    'color': "rgba(1,1,255,0.5)",
    'format': 'bed',
    'tracktype':'ROI',
    'donor':'all',
    'tissue':'all'
  },
  {
    "name": 'L1 insertions called by Alex Urban',
    'url': "./rois/urban_L1.chm13.bed",
    'indexed': false,
    'color': "rgba(99,99,99,0.5)",
    'format': 'bed',
    'tracktype':'ROI',
    'donor':'all',
    'tissue':'all'
  },
  {
"name": "D31 DURA KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D31.DURA.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D31",
"tissue":"DURA",
"order":4.9,
"height":25
},
{
"name": "D21 HIP KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D21.HIP.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D21",
"tissue":"HIP",
"order":4.9,
"height":25
},
{
"name": "D27 DLPFC KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D27.DLPFC.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D27",
"tissue":"DLPFC",
"order":4.9,
"height":25
},
{
"name": "D43 DURA KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D43.DURA.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D43",
"tissue":"DURA",
"order":4.9,
"height":25
},
{
"name": "D35 DURA KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D35.DURA.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D35",
"tissue":"DURA",
"order":4.9,
"height":25
},
{
"name": "D39 DURA KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D39.DURA.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D39",
"tissue":"DURA",
"order":4.9,
"height":25
},
{
"name": "D10 HIP KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D10.HIP.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D10",
"tissue":"HIP",
"order":4.9,
"height":25
},
{
"name": "D26 HIP KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D26.HIP.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D26",
"tissue":"HIP",
"order":4.9,
"height":25
},
{
"name": "D8 DURA KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D8.DURA.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D8",
"tissue":"DURA",
"order":4.9,
"height":25
},
{
"name": "D35 HIP KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D35.HIP.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D35",
"tissue":"HIP",
"order":4.9,
"height":25
},
{
"name": "D26 DLPFC KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D26.DLPFC.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D26",
"tissue":"DLPFC",
"order":4.9,
"height":25
},
{
"name": "D25 DURA KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D25.DURA.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D25",
"tissue":"DURA",
"order":4.9,
"height":25
},
{
"name": "D5 DLPFC KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D5.DLPFC.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D5",
"tissue":"DLPFC",
"order":4.9,
"height":25
},
{
"name": "D21 DURA KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D21.DURA.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D21",
"tissue":"DURA",
"order":4.9,
"height":25
},
{
"name": "D32 HIP KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D32.HIP.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D32",
"tissue":"HIP",
"order":4.9,
"height":25
},
{
"name": "D14 DURA KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D14.DURA.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D14",
"tissue":"DURA",
"order":4.9,
"height":25
},
{
"name": "D28 HIP KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D28.HIP.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D28",
"tissue":"HIP",
"order":4.9,
"height":25
},
{
"name": "D4 DURA KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D4.DURA.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D4",
"tissue":"DURA",
"order":4.9,
"height":25
},
{
"name": "D28 DLPFC KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D28.DLPFC.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D28",
"tissue":"DLPFC",
"order":4.9,
"height":25
},
{
"name": "D10 DURA KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D10.DURA.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D10",
"tissue":"DURA",
"order":4.9,
"height":25
},
{
"name": "D24 DURA KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D24.DURA.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D24",
"tissue":"DURA",
"order":4.9,
"height":25
},
{
"name": "D35 DLPFC KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D35.DLPFC.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D35",
"tissue":"DLPFC",
"order":4.9,
"height":25
},
{
"name": "D46 DLPFC KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D46.DLPFC.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D46",
"tissue":"DLPFC",
"order":4.9,
"height":25
},
{
"name": "D25 HIP KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D25.HIP.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D25",
"tissue":"HIP",
"order":4.9,
"height":25
},
{
"name": "D8 DLPFC KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D8.DLPFC.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D8",
"tissue":"DLPFC",
"order":4.9,
"height":25
},
{
"name": "D20 DURA KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D20.DURA.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D20",
"tissue":"DURA",
"order":4.9,
"height":25
},
{
"name": "D19 DURA KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D19.DURA.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D19",
"tissue":"DURA",
"order":4.9,
"height":25
},
{
"name": "D14 DLPFC KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D14.DLPFC.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D14",
"tissue":"DLPFC",
"order":4.9,
"height":25
},
{
"name": "D25 DLPFC KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D25.DLPFC.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D25",
"tissue":"DLPFC",
"order":4.9,
"height":25
},
{
"name": "D22 HIP KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D22.HIP.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D22",
"tissue":"HIP",
"order":4.9,
"height":25
},
{
"name": "D15 DURA KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D15.DURA.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D15",
"tissue":"DURA",
"order":4.9,
"height":25
},
{
"name": "D14 HIP KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D14.HIP.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D14",
"tissue":"HIP",
"order":4.9,
"height":25
},
{
"name": "D1 DURA KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D1.DURA.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D1",
"tissue":"DURA",
"order":4.9,
"height":25
},
{
"name": "D28 DURA KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D28.DURA.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D28",
"tissue":"DURA",
"order":4.9,
"height":25
},
{
"name": "D11 DURA KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D11.DURA.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D11",
"tissue":"DURA",
"order":4.9,
"height":25
},
{
"name": "D5 DURA KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D5.DURA.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D5",
"tissue":"DURA",
"order":4.9,
"height":25
},
{
"name": "D31 HIP KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D31.HIP.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D31",
"tissue":"HIP",
"order":4.9,
"height":25
},
{
"name": "D30 DURA KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D30.DURA.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D30",
"tissue":"DURA",
"order":4.9,
"height":25
},
{
"name": "D46 DURA KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D46.DURA.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D46",
"tissue":"DURA",
"order":4.9,
"height":25
},
{
"name": "D42 DURA KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D42.DURA.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D42",
"tissue":"DURA",
"order":4.9,
"height":25
},
{
"name": "D38 DURA KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D38.DURA.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D38",
"tissue":"DURA",
"order":4.9,
"height":25
},
{
"name": "D24 DLPFC KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D24.DLPFC.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D24",
"tissue":"DLPFC",
"order":4.9,
"height":25
},
{
"name": "D22 DURA KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D22.DURA.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D22",
"tissue":"DURA",
"order":4.9,
"height":25
},
{
"name": "D32 DLPFC KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D32.DLPFC.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D32",
"tissue":"DLPFC",
"order":4.9,
"height":25
},
{
"name": "D33 HIP KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D33.HIP.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D33",
"tissue":"HIP",
"order":4.9,
"height":25
},
{
"name": "D26 DURA KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D26.DURA.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D26",
"tissue":"DURA",
"order":4.9,
"height":25
},
{
"name": "D7 DURA KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D7.DURA.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D7",
"tissue":"DURA",
"order":4.9,
"height":25
},
{
"name": "D13 DURA KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D13.DURA.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D13",
"tissue":"DURA",
"order":4.9,
"height":25
},
{
"name": "D22 DLPFC KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D22.DLPFC.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D22",
"tissue":"DLPFC",
"order":4.9,
"height":25
},
{
"name": "D42 HIP KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D42.HIP.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D42",
"tissue":"HIP",
"order":4.9,
"height":25
},
{
"name": "D3 DURA KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D3.DURA.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D3",
"tissue":"DURA",
"order":4.9,
"height":25
},
{
"name": "D17 DURA KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D17.DURA.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D17",
"tissue":"DURA",
"order":4.9,
"height":25
},
{
"name": "D36 DURA KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D36.DURA.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D36",
"tissue":"DURA",
"order":4.9,
"height":25
},
{
"name": "D2 HIP KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D2.HIP.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D2",
"tissue":"HIP",
"order":4.9,
"height":25
},
{
"name": "D32 DURA KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D32.DURA.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D32",
"tissue":"DURA",
"order":4.9,
"height":25
},
{
"name": "D27 HIP KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D27.HIP.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D27",
"tissue":"HIP",
"order":4.9,
"height":25
},
{
"name": "D33 DLPFC KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D33.DLPFC.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D33",
"tissue":"DLPFC",
"order":4.9,
"height":25
},
{
"name": "D11 HIP KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D11.HIP.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D11",
"tissue":"HIP",
"order":4.9,
"height":25
},
{
"name": "D5 HIP KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D5.HIP.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D5",
"tissue":"HIP",
"order":4.9,
"height":25
},
{
"name": "D8 HIP KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D8.HIP.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D8",
"tissue":"HIP",
"order":4.9,
"height":25
},
{
"name": "D41 DURA KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D41.DURA.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D41",
"tissue":"DURA",
"order":4.9,
"height":25
},
{
"name": "D37 DURA KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D37.DURA.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D37",
"tissue":"DURA",
"order":4.9,
"height":25
},
{
"name": "D33 DURA KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D33.DURA.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D33",
"tissue":"DURA",
"order":4.9,
"height":25
},
{
"name": "D11 DLPFC KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D11.DLPFC.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D11",
"tissue":"DLPFC",
"order":4.9,
"height":25
},
{
"name": "D46 HIP KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D46.HIP.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D46",
"tissue":"HIP",
"order":4.9,
"height":25
},
{
"name": "D30 DLPFC KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D30.DLPFC.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D30",
"tissue":"DLPFC",
"order":4.9,
"height":25
},
{
"name": "D30 HIP KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D30.HIP.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D30",
"tissue":"HIP",
"order":4.9,
"height":25
},
{
"name": "D21 DLPFC KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D21.DLPFC.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D21",
"tissue":"DLPFC",
"order":4.9,
"height":25
},
{
"name": "D2 DLPFC KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D2.DLPFC.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D2",
"tissue":"DLPFC",
"order":4.9,
"height":25
},
{
"name": "D27 DURA KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D27.DURA.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D27",
"tissue":"DURA",
"order":4.9,
"height":25
},
{
"name": "D12 DURA KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D12.DURA.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D12",
"tissue":"DURA",
"order":4.9,
"height":25
},
{
"name": "D42 DLPFC KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D42.DLPFC.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D42",
"tissue":"DLPFC",
"order":4.9,
"height":25
},
{
"name": "D31 DLPFC KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D31.DLPFC.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D31",
"tissue":"DLPFC",
"order":4.9,
"height":25
},
{
"name": "D16 DURA KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D16.DURA.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D16",
"tissue":"DURA",
"order":4.9,
"height":25
},
{
"name": "D10 DLPFC KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D10.DLPFC.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D10",
"tissue":"DLPFC",
"order":4.9,
"height":25
},
{
"name": "D2 DURA KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D2.DURA.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D2",
"tissue":"DURA",
"order":4.9,
"height":25
},
{
"name": "D24 HIP KNRGL (MEGANE)",
"url":"./rois/megane_KNRGL_calls/D24.HIP.megane_final_gaussian.L1HS.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D24",
"tissue":"HIP",
"order":4.9,
"height":25
},
{
"name": "3prime Mike scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.sorted.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"all",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "Mike scL1 calls (≥10 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_10_single_donor_peaks.sorted.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"all",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "Mike scL1 calls (≥50 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_50_single_donor_peaks.sorted.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"all",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "Mike scL1 calls (≥10 read in target, ≤2 in off-target donor)",
"url":"./rois/mike_scL1_calls/2_10_single_donor_peaks.sorted.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"all",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "Mike scL1 calls (≥5 read in target, ≤2 in off-target donor)",
"url":"./rois/mike_scL1_calls/2_5_single_donor_peaks.sorted.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"all",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "Mike scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_single_donor_peaks.sorted.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"all",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "D37: scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.D37.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D37",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "D8: scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.D8.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D8",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "D30: scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.D30.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D30",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "D42: scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.D42.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D42",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "D1: scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.D1.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D1",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "D39: scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.D39.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D39",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "D28: scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.D28.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D28",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "D21: scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.D21.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D21",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "D26: scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.D26.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D26",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "D13: scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.D13.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D13",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "D14: scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.D14.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D14",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "D38: scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.D38.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D38",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "D7: scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.D7.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D7",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "D43: scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.D43.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D43",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "D31: scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.D31.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D31",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "D36: scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.D36.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D36",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "D15: scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.D15.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D15",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "D12: scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.D12.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D12",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "D27: scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.D27.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D27",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "D20: scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.D20.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D20",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "D11: scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.D11.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D11",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "D16: scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.D16.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D16",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "D24: scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.D24.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D24",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "D3: scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.D3.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D3",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "D4: scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.D4.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D4",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "D35: scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.D35.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D35",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "D32: scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.D32.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D32",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "D25: scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.D25.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D25",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "D22: scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.D22.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D22",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "D17: scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.D17.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D17",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "D10: scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.D10.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D10",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "D19: scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.D19.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D19",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "D33: scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.D33.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D33",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "D46: scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.D46.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D46",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "D5: scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.D5.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D5",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "D41: scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.D41.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D41",
"tissue":"all",
"order":4.95,
"height":25
},
{
"name": "D2: scL1 calls (≥5 read in target, ≤3 in off-target donor)",
"url":"./rois/mike_scL1_calls/3_5_3prime_single_donor_peaks.D2.bed",
"indexed":false,
"format":"bed",
"tracktype":"ROI",
"donor":"D2",
"tissue":"all",
"order":4.95,
"height":25
}];